# Generated by Django 4.1.1 on 2022-09-07 11:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('balanceapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beer',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('volume', models.FloatField(default=0.0)),
                ('since', models.DateTimeField(auto_now_add=True)),
                ('until', models.DateTimeField(auto_now=True)),
                ('related_beer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balanceapp.beer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
