# Generated by Django 4.1 on 2023-02-28 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('balanceapp', '0002_alert_balancedata_collectif_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(max_length=128),
        ),
        migrations.CreateModel(
            name='balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated', models.BooleanField()),
                ('remaining_beer', models.FloatField(default=0.0)),
                ('sentence_display', models.CharField(max_length=64)),
                ('related_beer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balanceapp.beer')),
            ],
        ),
    ]
