# Generated by Django 4.1.1 on 2022-09-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balanceapp', '0002_beer_created_at_beer_update_at_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='sale',
            name='since',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='until',
        ),
    ]
