# Generated by Django 4.1.1 on 2022-09-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balanceapp', '0003_alert_remove_sale_since_remove_sale_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='data',
            field=models.TextField(default=None),
        ),
    ]
