# Generated by Django 4.1 on 2023-04-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balanceapp', '0004_message_to_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='message_to_send',
            name='scroll',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
