# Generated by Django 4.1 on 2023-04-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balanceapp', '0005_message_to_send_scroll'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balance',
            old_name='sentence_display',
            new_name='nomComplet',
        ),
        migrations.AddField(
            model_name='balance',
            name='nameBeerOrCollective',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='balance',
            name='nomSimple',
            field=models.CharField(default='test', max_length=64),
            preserve_default=False,
        ),
    ]
