# Generated by Django 4.1 on 2024-09-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balanceapp', '0006_rename_sentence_display_balance_nomcomplet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
