# Generated by Django 4.1 on 2024-09-09 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balanceapp', '0007_alter_alert_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BalanceData',
            new_name='BoxData',
        ),
    ]
