# Generated by Django 4.1 on 2024-09-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balanceapp', '0008_rename_balancedata_boxdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='remaining_beer',
            field=models.IntegerField(default=0),
        ),
    ]
