# Generated by Django 4.1 on 2024-09-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balanceapp', '0009_alter_balance_remaining_beer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='data',
        ),
        migrations.AlterField(
            model_name='alert',
            name='type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Matrice defaut'), (2, 'Humidity'), (3, 'Temperature'), (4, 'B2 NOFut'), (5, 'B1 NOFut'), (6, 'B2 ENDFut'), (7, 'B1 ENDFut'), (8, 'B2 Unplug'), (9, 'B1 Unplug'), (10, 'NB B2 Defaut'), (11, 'NB B1 Defaut'), (12, 'B2 Def'), (13, 'B1 Def'), (14, 'Communication Defaut')], null=True),
        ),
    ]
